/**
 * DanceSteps.js
 * 
 * Programmed 16 choreography steps for MIRAI Dance Coach (Arabic Kuthu Hook).
 * Each step specifies the movement choreography, main tracking landmarks,
 * friendly guidance prompts, and canonical 2D joint coordinates.
 */

// Canonical REST pose coordinates (normalized 0.0 to 1.0)
export const REST_POSE_COORDINATES = {
  head: { x: 0.50, y: 0.20 },
  neck: { x: 0.50, y: 0.28 },
  leftShoulder: { x: 0.42, y: 0.29 },
  rightShoulder: { x: 0.58, y: 0.29 },
  leftElbow: { x: 0.38, y: 0.44 },
  rightElbow: { x: 0.62, y: 0.44 },
  leftHand: { x: 0.35, y: 0.62 },
  rightHand: { x: 0.65, y: 0.62 },
  leftHip: { x: 0.45, y: 0.55 },
  rightHip: { x: 0.55, y: 0.55 },
  leftKnee: { x: 0.44, y: 0.72 },
  rightKnee: { x: 0.56, y: 0.72 },
  leftFoot: { x: 0.43, y: 0.88 },
  rightFoot: { x: 0.57, y: 0.88 },
};

export const DANCE_STEPS = [
  // STEP 1 — Open Starting Pose
  {
    id: 'step_01_open_starting_pose',
    stepNumber: 1,
    name: 'Open Starting Pose',
    displayName: 'Open Stance',
    movement: 'Stand with both feet apart. Knees slightly bent. Both arms open away from the body. Elbows slightly bent. Hands/palms facing outward/upward. Head facing forward.',
    mainLandmarks: 'feet, knees, both shoulders, both elbows, both wrists',
    footLeg: 'Both feet apart, knees slightly bent',
    hipBody: 'Upright center stance',
    armsHands: 'Both arms open away from body, elbows slightly bent, hands outward/upward',
    head: 'Facing forward',
    description: 'Open Starting Pose: feet apart, knees slightly bent, both arms open away from body with elbows bent.',
    duration: 2.0,
    bpm: 105,
    difficulty: 'easy',
    movementType: 'Open Stance',
    bodyParts: ['feet', 'knees', 'shoulders', 'elbows', 'wrists', 'arms', 'legs'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.50, y: 0.20 },
      leftShoulder: { x: 0.42, y: 0.29 },
      rightShoulder: { x: 0.58, y: 0.29 },
      leftElbow: { x: 0.28, y: 0.44 },
      rightElbow: { x: 0.72, y: 0.44 },
      leftHand: { x: 0.22, y: 0.38 },
      rightHand: { x: 0.78, y: 0.38 },
      leftHip: { x: 0.45, y: 0.55 },
      rightHip: { x: 0.55, y: 0.55 },
      leftKnee: { x: 0.38, y: 0.73 },
      rightKnee: { x: 0.62, y: 0.73 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 2 — Hands Together
  {
    id: 'step_02_hands_together',
    stepNumber: 2,
    name: 'Hands Together',
    displayName: 'Hands Together',
    movement: 'Bring both hands toward the center of the body. Hands come close together around chest/face level. Elbows remain bent. Keep the legs in the wide stance.',
    mainLandmarks: 'left wrist + right wrist distance, elbow angles',
    footLeg: 'Wide stance maintained',
    hipBody: 'Upright center stance',
    armsHands: 'Hands together near chest/face level, elbows bent',
    head: 'Facing forward',
    description: 'Hands Together: bring hands toward center of body near chest/face level with elbows bent.',
    duration: 2.0,
    bpm: 105,
    difficulty: 'easy',
    movementType: 'Hands Together',
    bodyParts: ['wrists', 'elbows', 'arms'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.50, y: 0.20 },
      leftShoulder: { x: 0.42, y: 0.29 },
      rightShoulder: { x: 0.58, y: 0.29 },
      leftElbow: { x: 0.32, y: 0.38 },
      rightElbow: { x: 0.68, y: 0.38 },
      leftHand: { x: 0.46, y: 0.30 },
      rightHand: { x: 0.54, y: 0.30 },
      leftHip: { x: 0.45, y: 0.55 },
      rightHip: { x: 0.55, y: 0.55 },
      leftKnee: { x: 0.38, y: 0.73 },
      rightKnee: { x: 0.62, y: 0.73 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 3 — Open Both Hands
  {
    id: 'step_03_open_both_hands',
    stepNumber: 3,
    name: 'Open Both Hands',
    displayName: 'Open Hands',
    movement: 'Separate both hands again. Move both arms outward. Keep elbows slightly bent. Return to the open-arm groove.',
    mainLandmarks: 'shoulder → elbow → wrist positions',
    footLeg: 'Wide stance maintained',
    hipBody: 'Center groove',
    armsHands: 'Separate hands, move arms outward with elbows slightly bent',
    head: 'Facing forward',
    description: 'Open Both Hands: separate hands and move both arms outward into the open-arm groove.',
    duration: 2.0,
    bpm: 105,
    difficulty: 'easy',
    movementType: 'Open Hands',
    bodyParts: ['shoulders', 'elbows', 'wrists', 'arms'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.50, y: 0.20 },
      leftShoulder: { x: 0.42, y: 0.29 },
      rightShoulder: { x: 0.58, y: 0.29 },
      leftElbow: { x: 0.26, y: 0.42 },
      rightElbow: { x: 0.74, y: 0.42 },
      leftHand: { x: 0.18, y: 0.36 },
      rightHand: { x: 0.82, y: 0.36 },
      leftHip: { x: 0.45, y: 0.55 },
      rightHip: { x: 0.55, y: 0.55 },
      leftKnee: { x: 0.38, y: 0.73 },
      rightKnee: { x: 0.62, y: 0.73 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 4 — Right Body Groove
  {
    id: 'step_04_right_body_groove',
    stepNumber: 4,
    name: 'Right Body Groove',
    displayName: 'Right Groove',
    movement: 'Keep feet wide. Bend the knees slightly. Shift the upper body toward the right. Let the head tilt toward the right. Arms stay relaxed and open/downward.',
    mainLandmarks: 'hip shift + shoulder tilt + head + knees + open arms',
    footLeg: 'Feet wide, knees bent slightly',
    hipBody: 'Upper body shifts right with hip shift and shoulder tilt',
    armsHands: 'Arms relaxed, open and downward',
    head: 'Tilt head toward the right',
    description: 'Right Body Groove: shift upper body toward right, tilt head right, arms relaxed open/downward.',
    duration: 2.0,
    bpm: 105,
    difficulty: 'easy',
    movementType: 'Body Shift',
    bodyParts: ['right_hip', 'shoulders', 'head', 'knees', 'arms', 'legs'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.58, y: 0.23 },
      leftShoulder: { x: 0.48, y: 0.28 },
      rightShoulder: { x: 0.64, y: 0.34 },
      leftElbow: { x: 0.26, y: 0.42 },
      rightElbow: { x: 0.74, y: 0.46 },
      leftHand: { x: 0.16, y: 0.48 },
      rightHand: { x: 0.84, y: 0.54 },
      leftHip: { x: 0.50, y: 0.57 },
      rightHip: { x: 0.60, y: 0.57 },
      leftKnee: { x: 0.38, y: 0.73 },
      rightKnee: { x: 0.66, y: 0.76 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 5 — Hold Right Groove
  {
    id: 'step_05_hold_right_groove',
    stepNumber: 5,
    name: 'Hold Right Groove',
    displayName: 'Hold Right',
    movement: 'Maintain the right-side body position. Keep knees bent. Keep arms loose. Continue the small rhythmic bounce.',
    mainLandmarks: 'maintain the pose rather than moving the arms too much',
    footLeg: 'Knees bent, rhythmic bounce',
    hipBody: 'Maintain right-side body position',
    armsHands: 'Arms loose and relaxed',
    head: 'Tilted right with groove',
    description: 'Hold Right Groove: maintain the right-side position with small rhythmic bounce.',
    duration: 2.0,
    bpm: 105,
    difficulty: 'easy',
    movementType: 'Hold Groove',
    bodyParts: ['right_hip', 'right_knee', 'knees', 'hips', 'torso'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.55, y: 0.23 },
      leftShoulder: { x: 0.46, y: 0.31 },
      rightShoulder: { x: 0.62, y: 0.33 },
      leftElbow: { x: 0.34, y: 0.48 },
      rightElbow: { x: 0.74, y: 0.50 },
      leftHand: { x: 0.30, y: 0.58 },
      rightHand: { x: 0.78, y: 0.56 },
      leftHip: { x: 0.48, y: 0.58 },
      rightHip: { x: 0.58, y: 0.58 },
      leftKnee: { x: 0.38, y: 0.75 },
      rightKnee: { x: 0.64, y: 0.76 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 6 — Return Toward Center
  {
    id: 'step_06_return_toward_center',
    stepNumber: 6,
    name: 'Return Toward Center',
    displayName: 'Return Center',
    movement: 'Bring the body back toward the center. Keep the legs wide. Reduce the right-side lean. Arms remain relaxed.',
    mainLandmarks: 'hips, shoulders, torso, legs, arms',
    footLeg: 'Keep legs wide',
    hipBody: 'Body returns toward center, reduce lean',
    armsHands: 'Arms remain relaxed',
    head: 'Centered facing forward',
    description: 'Return Toward Center: bring body back toward center, legs wide, arms relaxed.',
    duration: 2.0,
    bpm: 105,
    difficulty: 'easy',
    movementType: 'Center Reset',
    bodyParts: ['hips', 'shoulders', 'torso', 'legs', 'arms'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.50, y: 0.20 },
      leftShoulder: { x: 0.42, y: 0.29 },
      rightShoulder: { x: 0.58, y: 0.29 },
      leftElbow: { x: 0.36, y: 0.45 },
      rightElbow: { x: 0.64, y: 0.45 },
      leftHand: { x: 0.35, y: 0.60 },
      rightHand: { x: 0.65, y: 0.60 },
      leftHip: { x: 0.45, y: 0.55 },
      rightHip: { x: 0.55, y: 0.55 },
      leftKnee: { x: 0.40, y: 0.73 },
      rightKnee: { x: 0.60, y: 0.73 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 7 — Left Body Groove
  {
    id: 'step_07_left_body_groove',
    stepNumber: 7,
    name: 'Left Body Groove',
    displayName: 'Left Groove',
    movement: 'Shift the body toward the left. Tilt the head toward the left. Keep knees slightly bent. Arms remain open/downward.',
    mainLandmarks: 'left hip + left shoulder + head + knees + open arms',
    footLeg: 'Feet wide, knees slightly bent',
    hipBody: 'Shift body toward left hip',
    armsHands: 'Arms remain open and downward',
    head: 'Tilt head toward the left',
    description: 'Left Body Groove: shift body toward left, tilt head left, arms open/downward.',
    duration: 2.0,
    bpm: 105,
    difficulty: 'easy',
    movementType: 'Body Shift',
    bodyParts: ['left_hip', 'left_shoulder', 'head', 'knees', 'arms', 'legs'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.42, y: 0.23 },
      leftShoulder: { x: 0.36, y: 0.34 },
      rightShoulder: { x: 0.52, y: 0.28 },
      leftElbow: { x: 0.26, y: 0.46 },
      rightElbow: { x: 0.74, y: 0.42 },
      leftHand: { x: 0.16, y: 0.54 },
      rightHand: { x: 0.84, y: 0.48 },
      leftHip: { x: 0.40, y: 0.57 },
      rightHip: { x: 0.50, y: 0.57 },
      leftKnee: { x: 0.34, y: 0.76 },
      rightKnee: { x: 0.62, y: 0.73 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 8 — Hold Left Groove
  {
    id: 'step_08_hold_left_groove',
    stepNumber: 8,
    name: 'Hold Left Groove',
    displayName: 'Hold Left',
    movement: 'Maintain the left-side lean. Continue the small knee/body bounce. Keep the arms relaxed.',
    mainLandmarks: 'left hip, left shoulder, knees, torso, arms',
    footLeg: 'Knees bent, rhythmic bounce',
    hipBody: 'Maintain left-side body position',
    armsHands: 'Keep arms relaxed',
    head: 'Tilted left with groove',
    description: 'Hold Left Groove: maintain left-side lean with continuous rhythmic knee/body bounce.',
    duration: 2.0,
    bpm: 105,
    difficulty: 'easy',
    movementType: 'Hold Groove',
    bodyParts: ['left_hip', 'left_shoulder', 'knees', 'hips', 'torso'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.45, y: 0.23 },
      leftShoulder: { x: 0.38, y: 0.33 },
      rightShoulder: { x: 0.54, y: 0.31 },
      leftElbow: { x: 0.26, y: 0.50 },
      rightElbow: { x: 0.66, y: 0.48 },
      leftHand: { x: 0.22, y: 0.56 },
      rightHand: { x: 0.70, y: 0.58 },
      leftHip: { x: 0.42, y: 0.58 },
      rightHip: { x: 0.52, y: 0.58 },
      leftKnee: { x: 0.36, y: 0.76 },
      rightKnee: { x: 0.62, y: 0.75 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 9 — Hands Toward Chest
  {
    id: 'step_09_hands_toward_chest',
    stepNumber: 9,
    name: 'Hands Toward Chest',
    displayName: 'Hands to Chest',
    movement: 'Bring the hands inward again. Both elbows bend. Hands come close to the chest. Body returns toward the center.',
    mainLandmarks: 'both wrists approaching the chest/center line',
    footLeg: 'Wide stance, knees slightly bent',
    hipBody: 'Body returns toward center',
    armsHands: 'Hands come close to chest, both elbows bend',
    head: 'Facing forward',
    description: 'Hands Toward Chest: bring hands inward close to the chest, body returning to center.',
    duration: 2.0,
    bpm: 105,
    difficulty: 'easy',
    movementType: 'Center Pull',
    bodyParts: ['wrists', 'elbows', 'arms', 'torso'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.50, y: 0.20 },
      leftShoulder: { x: 0.42, y: 0.29 },
      rightShoulder: { x: 0.58, y: 0.29 },
      leftElbow: { x: 0.32, y: 0.40 },
      rightElbow: { x: 0.68, y: 0.40 },
      leftHand: { x: 0.45, y: 0.36 },
      rightHand: { x: 0.55, y: 0.36 },
      leftHip: { x: 0.45, y: 0.55 },
      rightHip: { x: 0.55, y: 0.55 },
      leftKnee: { x: 0.39, y: 0.73 },
      rightKnee: { x: 0.61, y: 0.73 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 10 — Side-Oriented Movement
  {
    id: 'step_10_side_oriented_movement',
    stepNumber: 10,
    name: 'Side-Oriented Movement',
    displayName: 'Side Movement',
    movement: 'Turn/angle the upper body slightly toward one side. Keep the feet apart. One arm remains lower while the other begins the side gesture. Maintain the knee bend.',
    mainLandmarks: 'shoulders + hips + arms',
    footLeg: 'Feet apart, maintain knee bend',
    hipBody: 'Upper body angled slightly toward side',
    armsHands: 'One arm remains lower while other begins side gesture',
    head: 'Turned slightly sideways',
    description: 'Side-Oriented Movement: angle upper body sideways, feet apart, one arm lower while other begins gesture.',
    duration: 2.0,
    bpm: 105,
    difficulty: 'intermediate',
    movementType: 'Side Angle',
    bodyParts: ['shoulders', 'hips', 'arms', 'knees'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.52, y: 0.20 },
      leftShoulder: { x: 0.45, y: 0.29 },
      rightShoulder: { x: 0.59, y: 0.30 },
      leftElbow: { x: 0.34, y: 0.46 },
      rightElbow: { x: 0.66, y: 0.40 },
      leftHand: { x: 0.36, y: 0.54 },
      rightHand: { x: 0.72, y: 0.42 },
      leftHip: { x: 0.46, y: 0.55 },
      rightHip: { x: 0.56, y: 0.55 },
      leftKnee: { x: 0.40, y: 0.73 },
      rightKnee: { x: 0.64, y: 0.73 },
      leftFoot: { x: 0.36, y: 0.88 },
      rightFoot: { x: 0.68, y: 0.88 },
    },
  },

  // STEP 11 — Low Arm Sweep
  {
    id: 'step_11_low_arm_sweep',
    stepNumber: 11,
    name: 'Low Arm Sweep',
    displayName: 'Low Sweep',
    movement: 'Keep the body low. Move the hands/arms downward and across the front. Elbows stay slightly bent. Keep the wide stance.',
    mainLandmarks: 'wrist trajectory + elbow angles + knee bend',
    footLeg: 'Wide stance, body low, deep knee bend',
    hipBody: 'Grounded low posture',
    armsHands: 'Hands/arms sweep downward and across front, elbows slightly bent',
    head: 'Facing front',
    description: 'Low Arm Sweep: keep body low, sweep hands/arms downward and across front in wide stance.',
    duration: 2.0,
    bpm: 110,
    difficulty: 'intermediate',
    movementType: 'Low Sweep',
    bodyParts: ['wrists', 'elbows', 'knees', 'hips', 'arms'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.50, y: 0.22 },
      leftShoulder: { x: 0.42, y: 0.31 },
      rightShoulder: { x: 0.58, y: 0.31 },
      leftElbow: { x: 0.32, y: 0.48 },
      rightElbow: { x: 0.64, y: 0.46 },
      leftHand: { x: 0.40, y: 0.58 },
      rightHand: { x: 0.58, y: 0.56 },
      leftHip: { x: 0.44, y: 0.59 },
      rightHip: { x: 0.56, y: 0.59 },
      leftKnee: { x: 0.36, y: 0.76 },
      rightKnee: { x: 0.64, y: 0.76 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 12 — Continue the Groove
  {
    id: 'step_12_continue_the_groove',
    stepNumber: 12,
    name: 'Continue the Groove',
    displayName: 'Side Groove Shift',
    movement: 'Continue the side body movement. Shift body weight with the movement. Arms follow the body rather than staying completely still.',
    mainLandmarks: 'hips + legs + arms together',
    footLeg: 'Side foot step and weight shift',
    hipBody: 'Hips and upper body shift rhythmically',
    armsHands: 'Arms follow the lateral groove motion',
    head: 'Aligned with movement',
    description: 'Continue the Groove: side body movement, shifting body weight with arms following smoothly.',
    duration: 2.0,
    bpm: 110,
    difficulty: 'intermediate',
    movementType: 'Groove Shift',
    bodyParts: ['hips', 'legs', 'knees', 'arms', 'torso'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.44, y: 0.20 },
      leftShoulder: { x: 0.38, y: 0.29 },
      rightShoulder: { x: 0.54, y: 0.29 },
      leftElbow: { x: 0.28, y: 0.42 },
      rightElbow: { x: 0.64, y: 0.44 },
      leftHand: { x: 0.22, y: 0.46 },
      rightHand: { x: 0.58, y: 0.52 },
      leftHip: { x: 0.42, y: 0.56 },
      rightHip: { x: 0.52, y: 0.56 },
      leftKnee: { x: 0.32, y: 0.75 },
      rightKnee: { x: 0.66, y: 0.72 },
      leftFoot: { x: 0.30, y: 0.88 },
      rightFoot: { x: 0.74, y: 0.88 },
    },
  },

  // STEP 13 — Side Hand Gesture
  {
    id: 'step_13_side_hand_gesture',
    stepNumber: 13,
    name: 'Side Hand Gesture',
    displayName: 'Side Gesture',
    movement: 'Bring one hand outward into the side gesture/pointing motion visible in the clip. Opposite arm remains closer to the body. Body remains slightly angled.',
    mainLandmarks: 'active wrist + elbow + shoulder',
    footLeg: 'Wide anchored stance',
    hipBody: 'Body remains slightly angled',
    armsHands: 'One hand outward in side gesture, opposite arm closer to body',
    head: 'Looking toward side gesture',
    description: 'Side Hand Gesture: bring one hand outward into side gesture/pointing motion, opposite arm close.',
    duration: 2.0,
    bpm: 110,
    difficulty: 'intermediate',
    movementType: 'Side Gesture',
    bodyParts: ['pointing_wrist', 'elbow', 'shoulder', 'arms'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.52, y: 0.20 },
      leftShoulder: { x: 0.42, y: 0.29 },
      rightShoulder: { x: 0.58, y: 0.29 },
      leftElbow: { x: 0.32, y: 0.42 },
      rightElbow: { x: 0.68, y: 0.35 },
      leftHand: { x: 0.40, y: 0.48 },
      rightHand: { x: 0.82, y: 0.36 },
      leftHip: { x: 0.45, y: 0.55 },
      rightHip: { x: 0.55, y: 0.55 },
      leftKnee: { x: 0.38, y: 0.73 },
      rightKnee: { x: 0.62, y: 0.73 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 14 — Hands Back to Center
  {
    id: 'step_14_hands_back_to_center',
    stepNumber: 14,
    name: 'Hands Back to Center',
    displayName: 'Hands to Center',
    movement: 'Bring both hands back toward the center/chest. Elbows bend inward. Body comes back toward the center.',
    mainLandmarks: 'both wrists, elbows',
    footLeg: 'Wide stance, slight bounce',
    hipBody: 'Body returns to center',
    armsHands: 'Bring hands back toward chest, elbows bend inward',
    head: 'Facing forward',
    description: 'Hands Back to Center: bring both hands back toward chest, elbows bent inward, body at center.',
    duration: 2.0,
    bpm: 110,
    difficulty: 'easy',
    movementType: 'Center Clasp',
    bodyParts: ['wrists', 'elbows', 'arms', 'torso'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.50, y: 0.20 },
      leftShoulder: { x: 0.42, y: 0.29 },
      rightShoulder: { x: 0.58, y: 0.29 },
      leftElbow: { x: 0.33, y: 0.41 },
      rightElbow: { x: 0.67, y: 0.41 },
      leftHand: { x: 0.46, y: 0.36 },
      rightHand: { x: 0.54, y: 0.36 },
      leftHip: { x: 0.45, y: 0.55 },
      rightHip: { x: 0.55, y: 0.55 },
      leftKnee: { x: 0.39, y: 0.73 },
      rightKnee: { x: 0.61, y: 0.73 },
      leftFoot: { x: 0.35, y: 0.88 },
      rightFoot: { x: 0.65, y: 0.88 },
    },
  },

  // STEP 15 — Open-Arms Groove
  {
    id: 'step_15_open_arms_groove',
    stepNumber: 15,
    name: 'Open-Arms Groove',
    displayName: 'Open Groove',
    movement: 'Open both arms again. Feet remain wide. Knees bend. Body performs the rhythmic side groove. Head follows the body movement.',
    mainLandmarks: 'full body, arms, hips, knees',
    footLeg: 'Feet wide, knees bent',
    hipBody: 'Rhythmic full-body side groove',
    armsHands: 'Open both arms outward again',
    head: 'Follows body movement',
    description: 'Open-Arms Groove: open both arms, feet wide, knees bent, body performing rhythmic groove.',
    duration: 2.0,
    bpm: 115,
    difficulty: 'intermediate',
    movementType: 'Full Body Groove',
    bodyParts: ['full_body', 'arms', 'hips', 'knees'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.50, y: 0.21 },
      leftShoulder: { x: 0.42, y: 0.30 },
      rightShoulder: { x: 0.58, y: 0.30 },
      leftElbow: { x: 0.26, y: 0.40 },
      rightElbow: { x: 0.74, y: 0.40 },
      leftHand: { x: 0.18, y: 0.44 },
      rightHand: { x: 0.82, y: 0.44 },
      leftHip: { x: 0.44, y: 0.57 },
      rightHip: { x: 0.56, y: 0.57 },
      leftKnee: { x: 0.36, y: 0.75 },
      rightKnee: { x: 0.64, y: 0.75 },
      leftFoot: { x: 0.33, y: 0.88 },
      rightFoot: { x: 0.67, y: 0.88 },
    },
  },

  // STEP 16 — Final Hook Position
  {
    id: 'step_16_final_hook_position',
    stepNumber: 16,
    name: 'Final Hook Position',
    displayName: 'Final Hook Pose',
    movement: 'Maintain the wide stance. Keep the knees slightly bent. Arms remain in the final position from the clip. Complete the final body/head groove. Hold briefly before finishing.',
    mainLandmarks: 'full body',
    footLeg: 'Maintain wide stance, knees slightly bent',
    hipBody: 'Final body/head groove hold',
    armsHands: 'Final hook arm posture held firmly',
    head: 'Facing forward with attitude',
    description: 'Final Hook Position: maintain wide stance, knees bent, final hook arm pose, hold before finishing.',
    duration: 2.0,
    bpm: 115,
    difficulty: 'easy',
    movementType: 'Final Hold',
    bodyParts: ['full_body'],
    beats: 4,
    targetPose: {
      ...REST_POSE_COORDINATES,
      head: { x: 0.50, y: 0.20 },
      leftShoulder: { x: 0.42, y: 0.29 },
      rightShoulder: { x: 0.58, y: 0.29 },
      leftElbow: { x: 0.30, y: 0.42 },
      rightElbow: { x: 0.70, y: 0.37 },
      leftHand: { x: 0.24, y: 0.46 },
      rightHand: { x: 0.78, y: 0.34 },
      leftHip: { x: 0.45, y: 0.55 },
      rightHip: { x: 0.55, y: 0.55 },
      leftKnee: { x: 0.38, y: 0.73 },
      rightKnee: { x: 0.62, y: 0.73 },
      leftFoot: { x: 0.34, y: 0.88 },
      rightFoot: { x: 0.66, y: 0.88 },
    },
  },
];

export default DANCE_STEPS;
